name: Linting and Formatting on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  Continuous-Integration:
    name: Performs linting and code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linting Check
        run: npm run lint:check

      - name: Check Code Formatting
        run: npm run format:fix
