name: Linting and Formatting on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  Continuous-Integration:
    name: Performs linting and code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install 
<<<<<<< HEAD
=======

>>>>>>> 94ab68b8faf274f88c522e4ef02a2579efb0684c

