name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "ranazaeem1"
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ../../Dockerfile  # Adjust if Dockerfile is in a different location
        push: true
        tags: ranazaeem1/innobackend:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull ranazaeem1/innobackend:latest  # Replace with your Docker Hub username and repository
